{% set name = "brainglobe-utils" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 972863b10593ee9924bf6058e969ecba8f2e98c017ca600ed8004195cc0a5bdd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10.0
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8.0
    - natsort
    - pandas
    - psutil
    - pyarrow
    - slurmio
    - configobj
    - tqdm
    - nibabel
    - pyyaml
    - scipy
    - scikit-image
    - tifffile
    - numpy
    - qtpy
    - superqt
    - brainglobe-atlasapi >=2.0.1
    - brainglobe-space
    - requests
    - dask
    - numba
    - napari
    
test:
  imports:
    - brainglobe_utils
  commands:
    - pip list
    - pip check || true # ignore test due to HeapDict PyPI metadata issue
  requires:
    - pip

about:
  summary: Shared general purpose tools for the BrainGlobe project
  home: https://github.com/brainglobe/BrainGlobe-utils
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - alessandrofelder
